# Generated by Django 3.1.2 on 2020-11-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInmoAmanecer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='RUT',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
