# Generated by Django 3.1.2 on 2020-11-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=10)),
            ],
        ),
    ]
