# Generated by Django 3.1.2 on 2020-11-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInmobiliariaAmanecer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
