# Generated by Django 3.1.2 on 2020-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInmobiliariaAmanecer', '0003_auto_20201110_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
