# Generated by Django 3.1.2 on 2020-11-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInmobiliariaAmanecer', '0004_galeria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='galeria',
            table='galeria',
        ),
    ]
