# Generated by Django 3.1.2 on 2020-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInmobiliariaAmanecer', '0005_auto_20201113_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Galeria'),
        ),
    ]
