# Generated by Django 3.1.2 on 2020-11-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInmobiliariaAmanecer', '0006_auto_20201114_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombreCompleto',
            new_name='Nombre_Completo',
        ),
    ]
