# Generated by Django 3.1.2 on 2020-11-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInmobiliariaAmanecer', '0007_auto_20201114_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
    ]
